apiVersion: v1
kind: Pod
metadata:
  name: server-%ID%
  labels:
    app: "server"
    id: "%ID%"
spec:
  restartPolicy: Never
  containers:
  - name: server
    image: 0track/cassandra:5.1-accord-21
    imagePullPolicy: Always
    resources:
      requests:
        cpu: 1
    ports:
    - containerPort: 7000 # intra-node
    - containerPort: 7001 # tls-intra-node
    - containerPort: 7199 # jmx
    - containerPort: 9042 # cql
    env:
    - name: CASSANDRA_SEEDS
      value: "10.32.0.53"
    - name: CASSANDRA_DC
      value: "europe-west3"
    - name: CASSANDRA_NUM_TOKENS
      value: "1"
    - name: CASSANDRA_AUTO_BOOTSTRAP
      value: "false"
    - name: CASSANDRA_ENDPOINT_SNITCH
      value: "GoogleCloudSnitch"
    # - name: MAX_HEAP_SIZE
    #   value: "300M"
    # - name: HEAP_NEWSIZE
    #   value: "100M"

---
    
kind: Service
apiVersion: v1
metadata:
  name: "server"
spec:
  selector:
    app: "server"
  ports:
  - protocol: TCP
    port: 9042
    targetPort: 9042
  type: ClusterIP

