kind: Service
apiVersion: v1
metadata:
  name: "cassandra-ext"
spec:
  selector:
    app: "server"
  ports:
  - name: jmx
    protocol: TCP
    port: 7199
    targetPort: 7199
  - name: cql
    protocol: TCP
    port: 9042
    targetPort: 9042
  type: LoadBalancer
